import { OrderAddress } from "src/afi-manager-base-model/model/OrderAddress";

export const addressTemplates: OrderAddress[] = [
    {address:'100 The Highway',address2:'Unit 9 Big Yellow Self Storage',town:'London',postcode:'E1W 2BX'},
    {address:'199 East India Dock Road',address2:'199 East India Dock Road',town:'London',postcode:'E14 0ED'}, 
    {address:'27 Northumberland Gardens',address2:'27 Northumberland Gardens',town:'London',postcode:'N9 9LN'}, 
    {address:'22 Benedict Drive',address2:'22 Benedict Drive',town:'Feltham',postcode:'TW14 8JL'},
    {address:'Bendish Farm',address2:'Unit 2 The Grainstore',town:'Hertfordshire',postcode:'SG4 8JD',mustBeVerified:true},
    {address:'Bendish Farm',address2:'Mill House Trading',town:'Hertfordshire',postcode:'SG4 8JD',mustBeVerified:true}, 
    {address:'197 Campbell Road',address2:'197 Campbell Road',town:'London',postcode:'E3 4DP'}, 
    {address:'5 Henriques Street',address2:'5 Henriques Street',town:'London',postcode:'E1 1NB'}, 
    {address:'58 Shefford Crescent',address2:'58 Shefford Crescent Wokingham,Berkshire',town:'Wokingham',postcode:'RG40 1YP'},
    {address:'19-21 Park Royal Road,London',address2:'19-21 Park Royal Road',town:'London',postcode:'NW10 7LQ',mustBeVerified:true}, 
    {address:'Leeds Road',address2:'163 The Gatehaus',town:'Bradford',postcode:'BD1 5BQ'}, 
    {address:'216 Ramillies Road',address2:'216 Ramillies Road',town:'Sidcup',postcode:'DA15 9JH'}, 
    {address:'86 Deptford high street',address2:'86 Deptford high street',town:'London',postcode:'SE8 4RG'}, 
    {address:'4 Rockley Drive',address2:'4 Rockley Drive',town:'Wakefield',postcode:'WF2 7HQ'}, 
    {address:'20 Wrench Road',address2:'20 Wrench Road',town:'Norwich',postcode:'NR5 8AS'}, 
    {address:'9 St. Katherines Road',address2:'9 St. Katherines Road',town:'Erith',postcode:'DA18 4DS'}, 
    {address:'85 Footscray Road',address2:'85 Footscray Road',town:'London',postcode:'SE9 2SX'}, 
    {address:'23 Downland Way',address2:'23 Downland Way',town:'Epsom',postcode:'KT18 5SL'}, 
    {address:'5 Westfield Villas',address2:'5 Westfield Villas',town:'Doncaster',postcode:'DN7 6QA'}, 
    {address:'3 Henriques street,London',address2:'3 Henriques street',town:'London',postcode:'E1 1NB',mustBeVerified:true}, 
    {address:'207A Well Street',address2:'207A Well Street',town:'London',postcode:'E9 6QU'}, 
    {address:'35 Kendal Lane',address2:'35 Kendal Lane',town:'Leeds',postcode:'LS3 1AS'}, 
    {address:'Poyle Road',address2:'Chiltern Air Freight Ltd,Wraysbury House',town:'Slough',postcode:'SL3 0AY'}, 
    {address:'55 Bowens field',address2:'55 Bowens field',town:'Ashford',postcode:'TN23 4QW'}, 
    {address:'57 Sharrow Street',address2:'57 Sharrow Street',town:'Sheffield',postcode:'S11 8BY'}, 
    {address:'25 Dovehouse Close',address2:'25 Dovehouse Close',town:'St Neots',postcode:'PE19 1DS'}, 
    {address:'1 Powell Gardens',address2:'1 Powell Gardens',town:'Redhill',postcode:'RH1 1TQ'}, 
    {address:'212 Deptford High street',address2:'212 Deptford High street',town:'London',postcode:'SE8 3PR'}, 
    {address:'89 Hazel Close',address2:'89 Hazel Close',town:'Twickenham',postcode:'TW2 7NP'}, 
    {address:'232 Holloway Road',address2:'Flat 2, 232 Holloway Road',town:'London',postcode:'N7 8DA'}, 
    {address:'Challenge Road, Ashford, Middlesex',address2:'Unit 306 Bedfont North Industrial Estate',town:'Ashford',postcode:'TW15 1AX',mustBeVerified:true}, 
    {address:'59 Victoria Avenue',address2:'Flat 48 The Pinnacle',town:'Southend-on-sea',postcode:'SS2 6DS'}, 
    {address:'397 Hackney Road',address2:'Nail Stories',town:'London',postcode:'E2 8PP'}, 
    {address:'60 Westferry road',address2:'Flat 66 Ocean Wharf',town:'London',postcode:'E14 8JS'}, 
    {address:'46 Dominies Close',address2:'46 Dominies Close',town:'Rowlands Gill',postcode:'NE39 1PA'}, 
    {address:'41 High Street',address2:'41 High Street, Whitton',town:'Twickenham',postcode:'TW2 7LB'}, 
    {address:'72A High Street',address2:'72A High Street, Whitton',town:'Twickenham',postcode:'TW2 7LS'}, 
    {address:'Bibulo LTD,19-21 Park Royal Road',address2:'Unit 19, Bibulo LTD',town:'London',postcode:'NW10 7LQ',mustBeVerified:true}, {address:'Aurora Gardens',address2:'Apartment 33,Faraday House',town:'London',postcode:'SW11 8ED'}, 
    {address:'19-21 Park Royal Road',address2:'Unit 18,19-21 Park Royal Road',town:'London',postcode:'NW10 7LQ',mustBeVerified:true}, 
    {address:'Leaside Road',address2:'Unit G168 Riverside House',town:'London',postcode:'E5 9LU',mustBeVerified:true}, 
    {address:'2B Pemberton Terrace',address2:'2B Pemberton Terrace',town:'London',postcode:'N19 5RY'}, 
    {address:'180 Elsinge Road',address2:'180 Elsinge Road',town:'Enfield',postcode:'EN1 4PA'}, 
    {address:'36 Bournbrook Road',address2:'36 Bournbrook Road',town:'London',postcode:'SE3 8JS'}, 
    {address:'1 Ovett Gardens',address2:'1 Ovett Gardens, Gateshead',town:'Gateshead',postcode:'NE8 3JH'}, 
    {address:'21 Knightsbridge',address2:'Office 6 2nd Floor',town:'London',postcode:'SW1X 7LY'},
]